### ISSUE TITLE
Sample Event Tracker

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#38]
Hey @tadanna so this is the structure that we were using for tracking the events of the summit last year: https://docs.google.com/spreadsheets/d/1HKvDmxFsH54sS-TDLBG1NfiZqWoCW6zQ/edit?rtpof=true#gid=182813786
The columns in this doc will give you an idea on what data you need to gather and what steps you should track.

I'd suggest we proceed like this:
- [x] review the file
- [x] let me know if you have questions and we'll discuss them
- [x] create a sample github issue with a checklist that would work similarly to the spreadsheet
- [x] let's review together and finetune it
- [x] update the draft based on Asim's feedback
- [x] create a ticket for each upcoming test event 

Does this work for you?

_____

from @tadanna final version of the event tracker updated to February 2023: 

_Use the issue's comments to track updates, reminders and communications. Remove/Add sections where needed._

_______________

> _EVENT DETAILS_

**MEETUP GROUP**: Group name 
:point_right: **EVENT**: Event title

:link: Event page URL

:calendar: Date/Time: 

:busts_in_silhouette: Capacity: 

:round_pushpin: Location: 

:writing_hand: Organiser(s):

_______________

> _EVENT PREP_

General: 
- [ ] Define event details: type, date, topic
- [ ] Venue sourced? **before publishing the event**
- [ ] Publish event on Meetup **at least 2 weeks prior the date**
- [ ] Speaker sourced?

Meetup Page: 
- [ ] Check organiser's permissions on Meetup
- [ ] Event description & settings
- [ ] Event Cover
- [ ] Include venue in MeetUp event
- [ ] Publish Agenda

Extra notes:

**Comment by tadanna** [comment]
@holanita here a first draft. I'd like in our next call to review a couple of thing that are in the file you shared. 
 
_Use the comments to track updates, reminders and to-do. Remove/Add sections where needed._

_______________

> _EVENT DETAILS_

**MEETUP GROUP**: Group name 
:point_right: **EVENT**: Event title

:link: Event page URL

:calendar: Date/Time: 

:busts_in_silhouette: Capacity: 

:eight_spoked_asterisk: Type: Virtual / In-Person / Hybrid

_______________

> _CONTACTS_

- Organiser:
- Member Organisation:
- Email: 

_______________


> _EVENT PREP_

General: 
- [ ] Define event details: type, date, topic
- [ ] Speaker (if applicable)
- [ ] Promotion

Meetup Page: 
- [ ] Event description & settings
- [ ] Event Cover
- [ ] Publish Agenda

Extra notes:

_______________


> _POST EVENT_

- [ ] Zoom recording

**Comment by jawache** [comment]
Thanks @tadanna this looks like a good first step in tracking, close to what I was looking for. From my side these are the questions I will be asking to verify how likely an event is to actually being ready. The items might not be checked in order.

- [ ] Does the organizer have the right permissions to create the event in their group? Have other organizers been removed?
- [ ] Has a date/time been selected by the Organizer?
- [ ] Has a venue been sourced? (I just want to focus on in-person events, this is going to take time).
- [ ] Has an agenda been decided by the organizers?
- [ ] Have any speakers been sourced? (For these first events to be a remote speaker if that works/helps)
- [ ] Have any graphics been created that are needed? (we should eventually have a Canva template for cover images but for now they can be custom made by Jenya)
- [ ] Has the event been published on meetup.com **at least 2 weeks prior to the event date**? 2 weeks is a good number for meetup.


NOTE:

- They don't need to make a recording and we won't be publishing any recordings on our YouTube.
- To make sure this goes in the right direction just in-person is allowed, no virtual events.
- The first set of events have to be through our existing meetup groups. The stress of promotion shouldn't be a part of this, we have meetup groups with already hundreds of members - those should be the ones which we prioritise since there is already an existing audience who have already said they are interested in events in that region.
- We can be the ones clicking the buttons on meetup and working behind the scenes this first round but eventually the organizers have to be the ones creating their own events.
- Events have to be online 2 weeks prior to the date, that's the sweet spot for meetup.

**Comment by tadanna** [comment]
@jawache thanks for your comments, I have made some changes based on them and maybe we can discuss this further in our next call? 
In my mind this will be a collaborative tracker as much as possible, something the organisers use to keep track themselves of what they need to do, and where I can jump in to fill in if needed. 
Notes: 

- Many of the points you mentioned are already there, simply shortened with a description to make it concise. When possible, I would like the issue in GitHub to become the main place where communication happen instead of emails. If we will have things like templates, online guidelines (when Wiki is launched), I will add all these in the tracker as an extensive reference. 
- The event details at the top summarise the nature of the event with all its basic details. I will make sure we include direct links to the pages so that we have easy and fast access. Questions about time/date are ultimately answered when all this first part is filled out and are also outlined in the "general" section. 
- I have removed the promotion part as well as the post-event recording. 
- I have added a task to check the organisers permissions on meetup. Can you clarify why is it necessary to remove other organisers? Don't we want to have more in each group so that they can collaborate?
- I have removed the option of virtual/hybrid for now. Please keep in mind that I had mentioned in the emails I sent to reach out to the organisers that we prefer in-person but in the guidelines we still mention all 3 possible type of events. 
- Should we include a post-event attendance check box? to have an idea of how many people actually showed up? Or do you think it's not necessary?

@holanita FYI

 
_Use the issue's comments to track updates, reminders and communications. Remove/Add sections where needed._

_______________

> _EVENT DETAILS_

**MEETUP GROUP**: Group name 
:point_right: **EVENT**: Event title

:link: Event page URL

:calendar: Date/Time: 

:busts_in_silhouette: Capacity: 

:round_pushpin: Location: 

_______________

> _CONTACTS_

- Organiser:
- Member Organisation:
- Email: 

_______________


> _EVENT PREP_

General: 
- [ ] Define event details: type, date, topic
- [ ] Publish event on Meetup **at least 2 weeks prior the date**
- [ ] Speaker sourced?
- [ ] Setup Zoom event (or other chosen platform)

Meetup Page: 
- [ ] Check organiser's permissions on Meetup
- [ ] Event description & settings
- [ ] Event Cover
- [ ] Publish Agenda

Extra notes:

**Comment by tadanna** [comment]
@jawache @holanita here the final version of the tracker. I will share it with some of the people organising events and let's see how it works on this first round! 

_Use the issue's comments to track updates, reminders and communications. Remove/Add sections where needed._

_______________

> _EVENT DETAILS_

**MEETUP GROUP**: Group name 
:point_right: **EVENT**: Event title

:link: Event page URL

:calendar: Date/Time: 

:busts_in_silhouette: Capacity: 

:round_pushpin: Location: 

:writing_hand: Organiser

_______________


> _EVENT PREP_

General: 
- [ ] Define event details: type, date, topic
- [ ] Venue sourced? **before publishing the event**
- [ ] Publish event on Meetup **at least 2 weeks prior the date**
- [ ] Speaker sourced?

Meetup Page: 
- [ ] Check organiser's permissions on Meetup
- [ ] Event description & settings
- [ ] Event Cover
- [ ] Include venue in MeetUp event
- [ ] Publish Agenda

Extra notes:

**Comment by tadanna** [comment]
@holanita I updated the description with the latest version of the tracker - I am already using it for some events. Will close this ticket.
